### ISSUE TITLE
provide way to add additional öaw institutions as media owners

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/acdh-common-assets#11]
currently only acdh-ch shows up, project partners want to see their institution here as well, see example below

[Austrian Academy of Sciences](https://www.oeaw.ac.at/en/) 
Corporate body organized under public law (BGBl 569/1921 idF BGBl I 130/2003) 
 

Institute for Habsburg and Balkan Studies (IHB) Link: https://www.oeaw.ac.at/ihb/ 	 

Dr. Ignaz Seipel-Platz 2, 1010 Vienna, Austria 
E-Mail: [ihb@oeaw.ac.at](mailto:ihb@oeaw.ac.at) 

[Austrian Centre for Digital Humanities and Cultural Heritage (ACDH-CH)](https://acdh.oeaw.ac.at/) 
Dr. Ignaz Seipel-Platz 2, 1010 Vienna, Austria 
E-Mail: [acdh-tech@oeaw.ac.at](mailto:acdh-tech@oeaw.ac.at)

**Comment by stefanprobst** [comment]
does setting "responsiblePersons" in the redmine service issue work?

**Comment by csae8092** [comment]
good point, I'll try ...
